version: '3.8'

services:
  mongo:
    image: mongo:7.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - boilerplate-mongo-db:/data/db
    ports:
      - ${DATABASE_PORT}:27017

  api:
    build:
      context: .
      dockerfile: document.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./files:/usr/src/app/files

volumes:
  boilerplate-mongo-db:
