export const PRODUCT_ALL = {
  id: '$_id',
  category: { deletedAt: 0 },
  vendor: 1,
  country: 1,
  brand: 1,
  tags: 1,
  name: 1,
  code: 1,
  slug: 1,
  introduction: 1,
  barCode: 1,
  attributes: 1,
  images: 1,
  image: 1,
  quantity: 1,
  price: 1,
  _id: 1,
};

export const PRODUCT_ONE = {
  _id: 0,
  id: '$_id',
  category: { deletedAt: 0 },
  vendor: { $arrayElemAt: ['$vendor.name', 0] },
  country: { $arrayElemAt: ['$country.name', 0] },
  brand: { $arrayElemAt: ['$brand.name', 0] },
  tags: 1,
  name: 1,
  code: 1,
  slug: 1,
  introduction: 1,
  barCode: 1,
  attributes: 1,
  images: 1,
  image: 1,
  quantity: 1,
  price: 1,
};
