name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment commands via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/api.ludmila.vn
            git fetch origin
            git checkout dev  # Đảm bảo checkout đúng nhánh
            git reset --hard origin/dev  # Reset code để đồng bộ với remote
            docker-compose -f docker-compose.document.yaml down  # Dừng container cũ
            docker-compose -f docker-compose.document.yaml up -d --build
            systemctl restart nginx  # Không cần sudo nếu dùng root
